//This page is generated by ChatGPT as a placeholder.
//Remember to ask our client what they actually want in here (or whether they want it at all)
//Prompt: I really don't want to include any validation or actual functionality in the help page placeholder. Give me some placeholder simple and cute with MUI.
"use client";

import * as React from "react";
import {
  Box,
  Container,
  Paper,
  Typography,
  Stack,
  Button,
  Chip,
  Divider,
} from "@mui/material";
import HelpOutlineRoundedIcon from "@mui/icons-material/HelpOutlineRounded";
import FavoriteBorderRoundedIcon from "@mui/icons-material/FavoriteBorderRounded";

export default function HelpPage() {
  return (
    <Container maxWidth="md" sx={{ py: 6 }}>
      <Paper
        elevation={0}
        variant="outlined"
        sx={{
          p: { xs: 3, sm: 4 },
          borderRadius: 3,
          textAlign: "center",
        }}
      >
        <Stack spacing={2} alignItems="center">
          <Box
            sx={{
              width: 72,
              height: 72,
              borderRadius: "50%",
              display: "grid",
              placeItems: "center",
              bgcolor: "action.hover",
            }}
          >
            <HelpOutlineRoundedIcon fontSize="large" />
          </Box>

          <Typography variant="h4" sx={{ fontWeight: 600 }}>
            Help is on the way ✨
          </Typography>

          <Typography variant="body1" color="text.secondary" sx={{ maxWidth: 560 }}>
            We’re writing this page. For now, think of this as a cozy placeholder.
            Grab a tea, pet a cat, and check back soon.
          </Typography>

          <Stack direction="row" gap={1} sx={{ mt: 1 }}>
            <Chip label="FAQ" variant="outlined" />
            <Chip label="Contact" variant="outlined" />
            <Chip label="Policies" variant="outlined" />
          </Stack>

          <Divider flexItem sx={{ my: 1 }} />

          <Stack
            direction={{ xs: "column", sm: "row" }}
            spacing={1.5}
            justifyContent="center"
          >
            <Button variant="contained" disableElevation>
              Back to Dashboard
            </Button>
            <Button variant="text">Go to Settings</Button>
          </Stack>

          <Stack direction="row" spacing={0.5} alignItems="center" sx={{ mt: 1 }}>
            <FavoriteBorderRoundedIcon fontSize="small" />
            <Typography variant="caption" color="text.secondary">
              v0 — placeholder only
            </Typography>
          </Stack>
        </Stack>
      </Paper>
    </Container>
  );
}
